# Generated by Django 4.1.1 on 2023-03-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Актив', 'verbose_name_plural': 'Активы'},
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.IntegerField(max_length=100, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название актива'),
        ),
    ]
